apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  app: openshift-backup

namespace: openshift-etcd-backup

resources:
- etcd_clusterrolebinding.yml
- etcd_clusterrole.yml
- etcd_cronjob.yml
- etcd_project.yml
- etcd_sa.yml
